### ISSUE TITLE
Latest Policies

### ISSUE THREAD

**Issue by ankane** [creativecommons/policies#12]
Hi, thanks for making your policies CC0!

It looks like there are a number of revisions available on creativecommons.org that aren't available in this repo for the [terms of use](https://creativecommons.org/terms) and [privacy policy](https://creativecommons.org/privacy) (the latest are both dated 2019 and there a number of revisions in the right sidebar). Is there another place these documents are available?

**Comment by sarahpearson** [comment]
Good question! We stopped using this Github repository at some point along the way (and/or perhaps only used it sporadically). I *think* all of the revisions should at least be available online in the right sidebar of the current terms of use and privacy policy on the cc site. At a minimum, I can say for sure that we are now following that practice and have been for the past couple of years. 

(We will discuss internally whether and how to make that change in practice more clear here so we don't cause more confusion. Thanks!)

**Comment by ankane** [comment]
Thanks for the response!
