### ISSUE TITLE
Post revised privacy policy

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/policies#2]
Made a few small changes to make it clear the "No Access" section applies to CCID. This is ready to go live whenever you are, Matt.

**Comment by peterspdx** [comment]
Please be sure to note "last updated" at bottom, and provide a link to the earlier versions.  I still don't see that at the bottom of the policies page, the terms of service page, or the privacy page.  We should include links to prior versions their effective dates.  Thanks.

**Comment by sarahpearson** [comment]
Hey Matt: just noticed you've already created an archive for the privacy policies. Nice! Please hold off on pushing this privacy policy update live then because I'll need to make some changes to integrate the link to the archive at the bottom first. Actually, I'll close this issue out for now and create a new one once the update is ready.

**Comment by rios1223** [comment]
I need help with my issue
