### ISSUE TITLE
Repository for past versions of policies 

### ISSUE THREAD

**Issue by sarahpearson** [creativecommons/policies#4]
Moving Diane's comment from different thread here. 

Basically, we need a place where we store prior versions of the various policies (terms of service, privacy policy, /policies page) and their effective dates. Will link to that place from the bottom of each live policy.

**Comment by sarahpearson** [comment]
(Once we have that archive, then Diane and I can probably edit the policies directly without going through you since we both have access on Wordpress. We will still log on github so that we have a record of what is done and when.)

**Comment by rikicedot** [comment]
![img_20180529_234657_484](https://user-images.githubusercontent.com/40468484/42008182-64ffffec-7aae-11e8-9f82-2ebc1a02bd4d.jpg)
http://instagram.com/rikicdt_63/
