### ISSUE TITLE
Check this out...

### ISSUE THREAD

**Issue by mattl** [creativecommons/policies#5]
https://github.com/cc-icons/cc-icons

A font, mostly useful on the web, which has CC license graphics in the font.

![screenshot from 2015-03-06 11 53 35](https://cloud.githubusercontent.com/assets/33296/6529541/72af4812-c3f7-11e4-8f06-adabb5042449.png)

It would be nice to link to this from our downloads page.

**Comment by elliotharmon** [comment]
This is cool.

**Comment by sarahpearson** [comment]
@peterspdx Would you be okay with us linking to this from the /downloads page? I know we have historically pushed people to our versions of the logos/icons, so I wanted to make sure before doing anything with this. Thanks.

**Comment by janeatcc** [comment]
@mattl re "a suite of pictographic Creative Commons icons for easy scalable vector graphics" -- is a subset of this suitable for the platform communications kit which requires scalable logos? or is this completely different

**Comment by peterspdx** [comment]
I'm not comfortable posting a link to this from the /downloads page, at least not just yet.  There are trademark issues in play here, as I mentioned to Sarah today.  Please hold for now and I'll get back shortly.

**Comment by little-wow** [comment]
This predates me, and if you were uncomfortable putting up a link from the downloads page 4 years ago, I doubt anything has seriously changed? I'd say close it out, but @ericsteuer if you want to weigh in, please do!

**Comment by ericsteuer** [comment]
Nope. What Jennie said.
