### ISSUE TITLE
CC License plugin for Chromium, Chrome and Opera

### ISSUE THREAD

**Issue by mattl** [creativecommons/policies#6]
https://github.com/raulsi/CClicense

Uses several of our logos, this is a new project who has been talking to us. I'd like to invite them to work with us and fix up any issues.

**Comment by janeatcc** [comment]
Isn't that same as Open Attribute? Same folks?

On Tue, Mar 17, 2015 at 10:26 AM, Matt Lee <notifications@github.com> wrote:

> https://github.com/raulsi/CClicense
>
> Uses several of our logos, this is a new project who has been talking to
> us. I'd like to invite them to work with us and fix up any issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/policies/issues/6>.
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by mattl** [comment]
Not aware of OA.

Got a link?

**Comment by janeatcc** [comment]
http://openattribute.com/

Former CC Nathan Yergler worked on it, along with a bunch of other CC
related folks. I'm on the mailing list. Also, the wiki browser plugin page
points to OA as the new version, see https://wiki.creativecommons.org/MozCC.

On Tue, Mar 17, 2015 at 3:50 PM, Matt Lee <notifications@github.com> wrote:

> Not aware of OA.
>
> Got a link?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/creativecommons/policies/issues/6#issuecomment-82631560>
> .
>



-- 
Jane Park
@janedaily
Creative Commons | Los Angeles

Make a donation to support CC in 2015: http://bit.ly/supportcc2015

**Comment by peterspdx** [comment]
@janeatcc Helping determine what issues are still active and which can be closed in this archive. Is this still relevant and should be worked on by someone, and if so who?

**Comment by janeatcc** [comment]
For @kgodey to add to her revive or kill list, perhaps for google summer of code or other

**Comment by kgodey** [comment]
I added this to my list, I think we can close this issue @peterspdx.
